name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install tools
      run: |
        sudo apt update && sudo apt install -y make debhelper build-essential gcc-arm-linux-gnueabihf
    - name: build
      run: make release
    - name: package
      run: make deb
    - uses: actions/upload-artifact@v2
      with:
        name: docmon_0.1.0-1_amd64.deb
        path: target/release/docmon_0.1.0-1_amd64.deb 

